repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
    -   id: ruff
        args: [--fix, --unsafe-fixes]
    -   id: ruff-format
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.3
    hooks:
        - id: uv-lock
